/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TagihanRouteImport } from './routes/tagihan'
import { Route as SudahBayarRouteImport } from './routes/sudah-bayar'
import { Route as PindaiRouteImport } from './routes/pindai'
import { Route as PengaturanRouteImport } from './routes/pengaturan'
import { Route as PengajuanRouteImport } from './routes/pengajuan'
import { Route as PelangganRouteImport } from './routes/pelanggan'
import { Route as KasRouteImport } from './routes/kas'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BelumBayarRouteImport } from './routes/belum-bayar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PIndexRouteImport } from './routes/p.index'
import { Route as PortalTunggakanRouteImport } from './routes/portal/tunggakan'
import { Route as PortalRiwayatRouteImport } from './routes/portal/riwayat'
import { Route as PortalProfilRouteImport } from './routes/portal/profil'
import { Route as PortalPengaturanRouteImport } from './routes/portal/pengaturan'
import { Route as PortalBerandaRouteImport } from './routes/portal/beranda'
import { Route as PTokenRouteImport } from './routes/p.$token'

const TagihanRoute = TagihanRouteImport.update({
  id: '/tagihan',
  path: '/tagihan',
  getParentRoute: () => rootRouteImport,
} as any)
const SudahBayarRoute = SudahBayarRouteImport.update({
  id: '/sudah-bayar',
  path: '/sudah-bayar',
  getParentRoute: () => rootRouteImport,
} as any)
const PindaiRoute = PindaiRouteImport.update({
  id: '/pindai',
  path: '/pindai',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanRoute = PengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)
const PengajuanRoute = PengajuanRouteImport.update({
  id: '/pengajuan',
  path: '/pengajuan',
  getParentRoute: () => rootRouteImport,
} as any)
const PelangganRoute = PelangganRouteImport.update({
  id: '/pelanggan',
  path: '/pelanggan',
  getParentRoute: () => rootRouteImport,
} as any)
const KasRoute = KasRouteImport.update({
  id: '/kas',
  path: '/kas',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BelumBayarRoute = BelumBayarRouteImport.update({
  id: '/belum-bayar',
  path: '/belum-bayar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PIndexRoute = PIndexRouteImport.update({
  id: '/p/',
  path: '/p/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTunggakanRoute = PortalTunggakanRouteImport.update({
  id: '/portal/tunggakan',
  path: '/portal/tunggakan',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRiwayatRoute = PortalRiwayatRouteImport.update({
  id: '/portal/riwayat',
  path: '/portal/riwayat',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProfilRoute = PortalProfilRouteImport.update({
  id: '/portal/profil',
  path: '/portal/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPengaturanRoute = PortalPengaturanRouteImport.update({
  id: '/portal/pengaturan',
  path: '/portal/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalBerandaRoute = PortalBerandaRouteImport.update({
  id: '/portal/beranda',
  path: '/portal/beranda',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/belum-bayar': typeof BelumBayarRoute
  '/dashboard': typeof DashboardRoute
  '/kas': typeof KasRoute
  '/pelanggan': typeof PelangganRoute
  '/pengajuan': typeof PengajuanRoute
  '/pengaturan': typeof PengaturanRoute
  '/pindai': typeof PindaiRoute
  '/sudah-bayar': typeof SudahBayarRoute
  '/tagihan': typeof TagihanRoute
  '/p/$token': typeof PTokenRoute
  '/portal/beranda': typeof PortalBerandaRoute
  '/portal/pengaturan': typeof PortalPengaturanRoute
  '/portal/profil': typeof PortalProfilRoute
  '/portal/riwayat': typeof PortalRiwayatRoute
  '/portal/tunggakan': typeof PortalTunggakanRoute
  '/p/': typeof PIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/belum-bayar': typeof BelumBayarRoute
  '/dashboard': typeof DashboardRoute
  '/kas': typeof KasRoute
  '/pelanggan': typeof PelangganRoute
  '/pengajuan': typeof PengajuanRoute
  '/pengaturan': typeof PengaturanRoute
  '/pindai': typeof PindaiRoute
  '/sudah-bayar': typeof SudahBayarRoute
  '/tagihan': typeof TagihanRoute
  '/p/$token': typeof PTokenRoute
  '/portal/beranda': typeof PortalBerandaRoute
  '/portal/pengaturan': typeof PortalPengaturanRoute
  '/portal/profil': typeof PortalProfilRoute
  '/portal/riwayat': typeof PortalRiwayatRoute
  '/portal/tunggakan': typeof PortalTunggakanRoute
  '/p': typeof PIndexRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/belum-bayar': typeof BelumBayarRoute
  '/dashboard': typeof DashboardRoute
  '/kas': typeof KasRoute
  '/pelanggan': typeof PelangganRoute
  '/pengajuan': typeof PengajuanRoute
  '/pengaturan': typeof PengaturanRoute
  '/pindai': typeof PindaiRoute
  '/sudah-bayar': typeof SudahBayarRoute
  '/tagihan': typeof TagihanRoute
  '/p/$token': typeof PTokenRoute
  '/portal/beranda': typeof PortalBerandaRoute
  '/portal/pengaturan': typeof PortalPengaturanRoute
  '/portal/profil': typeof PortalProfilRoute
  '/portal/riwayat': typeof PortalRiwayatRoute
  '/portal/tunggakan': typeof PortalTunggakanRoute
  '/p/': typeof PIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/belum-bayar'
    | '/dashboard'
    | '/kas'
    | '/pelanggan'
    | '/pengajuan'
    | '/pengaturan'
    | '/pindai'
    | '/sudah-bayar'
    | '/tagihan'
    | '/p/$token'
    | '/portal/beranda'
    | '/portal/pengaturan'
    | '/portal/profil'
    | '/portal/riwayat'
    | '/portal/tunggakan'
    | '/p/'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/belum-bayar'
    | '/dashboard'
    | '/kas'
    | '/pelanggan'
    | '/pengajuan'
    | '/pengaturan'
    | '/pindai'
    | '/sudah-bayar'
    | '/tagihan'
    | '/p/$token'
    | '/portal/beranda'
    | '/portal/pengaturan'
    | '/portal/profil'
    | '/portal/riwayat'
    | '/portal/tunggakan'
    | '/p'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/belum-bayar'
    | '/dashboard'
    | '/kas'
    | '/pelanggan'
    | '/pengajuan'
    | '/pengaturan'
    | '/pindai'
    | '/sudah-bayar'
    | '/tagihan'
    | '/p/$token'
    | '/portal/beranda'
    | '/portal/pengaturan'
    | '/portal/profil'
    | '/portal/riwayat'
    | '/portal/tunggakan'
    | '/p/'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BelumBayarRoute: typeof BelumBayarRoute
  DashboardRoute: typeof DashboardRoute
  KasRoute: typeof KasRoute
  PelangganRoute: typeof PelangganRoute
  PengajuanRoute: typeof PengajuanRoute
  PengaturanRoute: typeof PengaturanRoute
  PindaiRoute: typeof PindaiRoute
  SudahBayarRoute: typeof SudahBayarRoute
  TagihanRoute: typeof TagihanRoute
  PTokenRoute: typeof PTokenRoute
  PortalBerandaRoute: typeof PortalBerandaRoute
  PortalPengaturanRoute: typeof PortalPengaturanRoute
  PortalProfilRoute: typeof PortalProfilRoute
  PortalRiwayatRoute: typeof PortalRiwayatRoute
  PortalTunggakanRoute: typeof PortalTunggakanRoute
  PIndexRoute: typeof PIndexRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tagihan': {
      id: '/tagihan'
      path: '/tagihan'
      fullPath: '/tagihan'
      preLoaderRoute: typeof TagihanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sudah-bayar': {
      id: '/sudah-bayar'
      path: '/sudah-bayar'
      fullPath: '/sudah-bayar'
      preLoaderRoute: typeof SudahBayarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pindai': {
      id: '/pindai'
      path: '/pindai'
      fullPath: '/pindai'
      preLoaderRoute: typeof PindaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan': {
      id: '/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof PengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengajuan': {
      id: '/pengajuan'
      path: '/pengajuan'
      fullPath: '/pengajuan'
      preLoaderRoute: typeof PengajuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelanggan': {
      id: '/pelanggan'
      path: '/pelanggan'
      fullPath: '/pelanggan'
      preLoaderRoute: typeof PelangganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kas': {
      id: '/kas'
      path: '/kas'
      fullPath: '/kas'
      preLoaderRoute: typeof KasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/belum-bayar': {
      id: '/belum-bayar'
      path: '/belum-bayar'
      fullPath: '/belum-bayar'
      preLoaderRoute: typeof BelumBayarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/': {
      id: '/p/'
      path: '/p'
      fullPath: '/p/'
      preLoaderRoute: typeof PIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/tunggakan': {
      id: '/portal/tunggakan'
      path: '/portal/tunggakan'
      fullPath: '/portal/tunggakan'
      preLoaderRoute: typeof PortalTunggakanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/riwayat': {
      id: '/portal/riwayat'
      path: '/portal/riwayat'
      fullPath: '/portal/riwayat'
      preLoaderRoute: typeof PortalRiwayatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/profil': {
      id: '/portal/profil'
      path: '/portal/profil'
      fullPath: '/portal/profil'
      preLoaderRoute: typeof PortalProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/pengaturan': {
      id: '/portal/pengaturan'
      path: '/portal/pengaturan'
      fullPath: '/portal/pengaturan'
      preLoaderRoute: typeof PortalPengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/beranda': {
      id: '/portal/beranda'
      path: '/portal/beranda'
      fullPath: '/portal/beranda'
      preLoaderRoute: typeof PortalBerandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BelumBayarRoute: BelumBayarRoute,
  DashboardRoute: DashboardRoute,
  KasRoute: KasRoute,
  PelangganRoute: PelangganRoute,
  PengajuanRoute: PengajuanRoute,
  PengaturanRoute: PengaturanRoute,
  PindaiRoute: PindaiRoute,
  SudahBayarRoute: SudahBayarRoute,
  TagihanRoute: TagihanRoute,
  PTokenRoute: PTokenRoute,
  PortalBerandaRoute: PortalBerandaRoute,
  PortalPengaturanRoute: PortalPengaturanRoute,
  PortalProfilRoute: PortalProfilRoute,
  PortalRiwayatRoute: PortalRiwayatRoute,
  PortalTunggakanRoute: PortalTunggakanRoute,
  PIndexRoute: PIndexRoute,
  PortalIndexRoute: PortalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
